table medals
	lineageTag: 3d686db1-37d8-4f0f-9907-4d47af9429b7

	column medal_type
		dataType: string
		lineageTag: 70051bf5-c869-450d-a2c1-96bc24d0aaf5
		summarizeBy: none
		sourceColumn: medal_type

		annotation SummarizationSetBy = Automatic

	column medal_code
		dataType: int64
		formatString: 0
		lineageTag: 1d5fa472-9b07-42fa-ab07-e4399ddf3d69
		summarizeBy: sum
		sourceColumn: medal_code

		annotation SummarizationSetBy = Automatic

	column medal_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 025f7e3f-3e10-4834-9315-ca132dc2c869
		summarizeBy: none
		sourceColumn: medal_date

		variation Variation
			isDefault
			relationship: f20d993a-d20f-4158-9a4f-3ce37e2ec0e9
			defaultHierarchy: LocalDateTable_eebf603e-d3fc-4ff8-ad59-11220f02442b.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column name
		dataType: string
		lineageTag: c550f484-6ca6-4bd0-b8c5-1e9207cf7f46
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column country_code
		dataType: string
		lineageTag: 17fd55a4-41dd-46f3-b16a-09929abb8200
		summarizeBy: none
		sourceColumn: country_code

		annotation SummarizationSetBy = Automatic

	column gender
		dataType: string
		lineageTag: 703f6b6a-0079-4f2b-bf4d-0c7fe0b2d5c6
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = Automatic

	column discipline
		dataType: string
		lineageTag: 8cc1eba9-19e5-4290-82e5-be9de2268230
		summarizeBy: none
		sourceColumn: discipline

		annotation SummarizationSetBy = Automatic

	column event
		dataType: string
		lineageTag: 1a64a8a9-f978-42e8-a0f4-e659d6a08d0e
		summarizeBy: none
		sourceColumn: event

		annotation SummarizationSetBy = Automatic

	column event_type
		dataType: string
		lineageTag: 344137e1-76f0-4be1-8985-d9a9688fc63a
		summarizeBy: none
		sourceColumn: event_type

		annotation SummarizationSetBy = Automatic

	column url_event
		dataType: string
		lineageTag: 1bfebdcc-ca78-4290-93bd-b43e2d8aa17e
		summarizeBy: none
		sourceColumn: url_event

		annotation SummarizationSetBy = Automatic

	column code
		dataType: string
		lineageTag: aa4e0f0b-7d4e-4da9-b2c8-6a88fcb6d939
		summarizeBy: none
		sourceColumn: code

		annotation SummarizationSetBy = Automatic

	partition medals = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\Douglas Guilherme\Documents\Estudo BI\DataSet\geral\medals.csv"),[Delimiter=",", Columns=11, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"medal_type", type text}, {"medal_code", Int64.Type}, {"medal_date", type date}, {"name", type text}, {"country_code", type text}, {"gender", type text}, {"discipline", type text}, {"event", type text}, {"event_type", type text}, {"url_event", type text}, {"code", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

